### ISSUE TITLE
convert to node server

### ISSUE THREAD

**Issue by ungoldman** [PDXNode/pdxnode.org#1]
As discussed in today's organizer meeting and previously in pdxnode/pdxnode#81, we've talked about moving the site to a host that supports node, so organizers and attendees have a nice easy project to contribute to that's part of the meetup group.

I've volunteered to host the site on my [DO](https://digitalocean.com) droplet until we can secure sponsorship for server costs (if we go with DO, $5/mo for the basic droplet should get us all we need).

@obensource: I'll need to coordinate with you to point DNS to a new IP address when the time is right. Do you have access to that?

btw, looks like @hackygolucky's contact info is still there in the whois info (hi tracy! 👋 )

**Comment by obensource** [comment]
Woop! Thanks @ungoldman! (Also, Hi x 2 @hackygolucky! 👋)

I actually don't have ownership or authorization of this domain. I _think_ Tracy owns it most likely and we'll need to coordinate with her or whoever has the keys.

Now is a great time to take that off her shoulders and add it to our digital services sponsorship budget.

Thanks for pushing this forward.

**Comment by ungoldman** [comment]
Got something *extremely* basic going in `ng/node` branch. Test deploy living at http://pdxnode.valis.pw for now (see [404](http://pdxnode.valis.pw/404), [api](http://pdxnode.valis.pw/api)).

Honestly it's been a really long time since I've built a node server for serving front end content -- I just tried spinning up the latest version of express with ejs templates. Feels very dated.

Maybe we should try the more modern thing of serving up a single page app? I'm open to react or preact or whatever's the new hotness that people want to experiment with. My current favorite is https://choo.io.

**Comment by obensource** [comment]
![totally rad](https://media.giphy.com/media/STq727CknrFu0/giphy.gif)

@ungoldman I'm fine with react or choo–mostly because I'm most familiar with react and you're familiar with both.

**Comment by obensource** [comment]
.gifs are hard on mobile.

**Comment by ungoldman** [comment]
Going to close this as the static site is working fine. Broke out the module download stats demo I did into a separate repo: https://github.com/ungoldman/module-downloads

**Comment by obensource** [comment]
@ungoldman nice–your module-stats site is super cool! 🙌 

Good call on closing this issue. It seems that we just never found the time to move the site towards a Node.js app, but it's a great resource to point folks to! Thank you for contributing in such a meaningful way! 🍻
